<?php
return array (
  'app' => 'Admin',
  'model' => 'Subscribe',
  'action' => 'Index',
  'data' => '',
  'type' => '1',
  'status' => '1',
  'name' => '预约管理',
  'icon' => '',
  'remark' => '预约管理',
  'listorder' => '0',
  'children' => 
  array (
    array (
      'app' => 'Admin',
      'model' => 'Subscribe',
      'action' => 'Order',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '信息记录',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Subscribe',
      'action' => 'Teacher',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '预约医师',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Subscribe',
      'action' => 'Items',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '预约项目',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Subscribe',
      'action' => 'Pub',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '预约酒店',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
  ),
);