<?php
return array (
  'app' => 'Admin',
  'model' => 'Goods',
  'action' => 'index',
  'data' => '',
  'type' => '1',
  'status' => '1',
  'name' => '产品管理',
  'icon' => '',
  'remark' => '',
  'listorder' => '0',
  'children' => 
  array (
    array (
      'app' => 'Admin',
      'model' => 'Goods',
      'action' => 'Goods',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '产品记录',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Goods',
      'action' => 'Goodsadd',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '添加产品',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
  ),
);